### GET request with disabled redirects
# @no-redirect
GET http://localhost:3000/proxy/?url=https://www.newpharma.fr&engine=chrome

### GET request with disabled redirects
# @no-redirect
GET http://localhost:3000/proxy/?url=http://localhost:8083/project&engine=chrome
