# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CAC-Proxy Development

on:
  workflow_dispatch:

  push:
    branches:
    - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 'dev'
          token: ${{secrets.GCOLLIN_ACTIONS_TOKEN}}
      - name: Use Node.js version 16
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: Install
        run: |
          npx @puppeteer/browsers install chrome@stable
          npm install
      - name: Unit Tests
        run: |
          npm run test
